contact/urls.py
from django.urls import path
from contact import views


app_name = 'contact'

urlpatterns = [
    path('',views.index, name='index'),
    path('search/',views.search, name='search'),

    # contact (CRUD)
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    

    # user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),

    
    
    # path('<int:contact_id>/delete/',views.contact, name='contact'),
    # path('<int:contact_id>/detail/',views.contact, name='contact'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

contact/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from . import models

class Contact_Form(forms.ModelForm):
    picture = forms.ImageField(
        required=False,
        widget = forms.FileInput(
            attrs={
                'accept': 'image/*'
            }
        ),
       
    )

    first_name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'Nome',
            }
        ),
        label="Nome",
        help_text='Texto de ajuda para o usuário'
    )


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.fields['first_name'].widgets.attrs.update({
        #     'class': 'classe-a classe-b',
        #     'placeholder': 'Nome',
        # })


    class Meta:
        model = models.Contact
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
            'description',
            'category',
            'picture',
        )
        # widgets = {
        #     'first_name': forms.TextInput(
        #         attrs={
        #             'class': 'classe-a classe-b',
        #             'placeholder': 'Nome',
        #         }
        #     )
        # }

    def clean(self):
        
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        
        if first_name == last_name:
            msg_error = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid',
            )
            self.add_error('first_name', msg_error)
            self.add_error('last_name', msg_error)



        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        if first_name == "ABC":
            self.add_error(
                'first_name',
                ValidationError(
                    'Não é possível adicionar ABC nesse campo',
                    code='invalid',
                )
            )

        if len(first_name) <= 3:
            self.add_error(
                'first_name',
                ValidationError(
                    'Mínimo 4 caracteres',
                    code='invalid',
                )
            )

        
        return first_name
    


class ConfirmationForm(forms.Form):
    confirm_delete = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.CheckboxInput(attrs={'class': 'confirmation-checkbox'})
    )
    
class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
            required=True,
            min_length=3,
        )
    last_name = forms.CharField(
            required=True,
            min_length=3,
        )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )

        return email
    

class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

contact/views/contact_forms.py
from django.shortcuts import render , redirect, get_object_or_404
from contact.forms import Contact_Form
from django.urls import reverse
from contact.models import Contact
from contact.forms import ConfirmationForm
from django.contrib.auth.decorators import login_required
import os
from datetime import datetime
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

@login_required(login_url='contact:login')
def create(request):
    
    form_action = reverse('contact:create')
    

    if request.method == 'POST':
        form = Contact_Form(request.POST, request.FILES)
        
        context = {
            'form' : form,
            'form_action': form_action,
        }

        
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            # contact = form.save(commit=False)
            # contact.show = False
            # contact.save()
            # if contact.picture:
            #     original_file_name = contact.picture.name

            #     # Criar novo nome de arquivo
            #     date_str = datetime.now().strftime("%Y%m%d")
            #     y = datetime.now().strftime("%Y")
            #     m = datetime.now().strftime("%m")
            #     d = datetime.now().strftime("%d")
            #     file_name = os.path.basename(original_file_name)
            #     new_file_name = f'pictures/{y}/{m}/{d}_{contact.id}_{file_name}'

            #     # Copiar o arquivo para o novo nome
            #     if default_storage.exists(original_file_name):
            #         file_content = default_storage.open(original_file_name).read()
            #         default_storage.save(new_file_name, ContentFile(file_content))

            #         # Atualizar o campo 'picture' no modelo Contact
            #         contact.picture.name = new_file_name
            #         contact.save()

            #         # Excluir o arquivo antigo
            #         default_storage.delete(original_file_name)
            #         print(f'É ESSE AQUI >>>>> {original_file_name}')

                
            
            return redirect('contact:update', contact_id= contact.id)

        return render(
        request,
        'contact/create.html',
        context
        )

    context = {
        'form' : Contact_Form(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
        )

@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True , owner = request.user)
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = Contact_Form(request.POST, request.FILES, instance=contact)
        old_name = contact.picture.name
        
        context = {
            'form' : form,
            'form_action': form_action,
        }

        if form.is_valid():
            
            # contact = form.save(commit=False)
            # contact.show = False
            contact.save()
            # if 'picture' in request.FILES:
                
            #     new_picture = request.FILES['picture']
            #     print(new_picture.name)
            #     print(contact.picture.name)
            #     if new_picture.name != old_name:
            #         print('ENTROU')
            #         original_file_name = new_picture.name
            #         date_str = datetime.now().strftime("%Y%m%d")
            #         y = datetime.now().strftime("%Y")
            #         m = datetime.now().strftime("%m")
            #         d = datetime.now().strftime("%d")
            #         file_name = os.path.basename(original_file_name)
            #         new_file_name = f'{d}_{contact.id}_{file_name}'
            #         # contact.picture.name = new_file_name
            #         print(f'ESSE AQUI >>> {new_file_name}')
            #         contact.picture.save(new_file_name, ContentFile(new_picture.read()), save=False)
                

            # contact = form.save()


            return redirect('contact:update', contact_id= contact.id)

        return render(
        request,
        'contact/create.html',
        context
        )

    context = {
        'form' : Contact_Form(instance=contact),
        'form_action': form_action,
    }

    return render(
    request,
    'contact/create.html',
    context
    )

@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner = request.user)

    # Se a requisição for POST, crie o ConfirmationForm com dados do POST
    if request.method == 'POST':
        confirmation_form = ConfirmationForm(request.POST)

        # Verifica se o formulário de confirmação é válido
        if confirmation_form.is_valid():
            contact.delete()
            return redirect('contact:index')
    else:
        # Se a requisição não for POST, crie um ConfirmationForm vazio
        confirmation_form = ConfirmationForm()

    context = {
        'form': Contact_Form(instance=contact),  # Formulário de edição do contato
        'confirmation_form': confirmation_form,  # Formulário de confirmação
        'contact': contact  # Informações do contato
    }

    return render(
        request,
        'contact/update.html',  # O template de edição do contato
        context
    )

contact/views/contact_views.py
from django.shortcuts import render , get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contact
from django.http import Http404
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - ',
    }

    return render(
    request,
    'contact/index.html',
    context
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects.filter(show=True).filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value) 
        ).order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Search - ',
    }

    return render(
    request,
    'contact/index.html',
    context
    )

def contact(request,contact_id):
    # single_contact = Contact.objects.filter(id=contact_id).first()
    single_contact = get_object_or_404(Contact.objects.filter( id = contact_id, show=True))

    # if single_contact is None:
    #     raise Http404()

    context = {
        'contact': single_contact,
        'site_title': f'{single_contact.first_name} {single_contact.last_name} - '
    }

    return render(
    request,
    'contact/contact.html',
    context
    )

contact/views/user_forms.py
from django.shortcuts import render , redirect
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages
from django.contrib import auth, messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,"Usuário registrado")
            return redirect('contact:login')

    return render(
        request,
        'contact/register.html',
        {
            'form':form
        }
    )

def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('contact:index')
        messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/login.html',
        {
            'form': form
        }
    )

@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')


@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )


    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )
    
    form.save()
    return redirect('contact:user_update')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{contact.last_name}}
        </h1>

        <p><b>ID:</b> {{contact.id}} </p>
        <p><b>E-mail:</b> {{contact.email}} </p>
        <p><b>Phone:</b> {{contact.phone}} </p>
        <p><b>Created Date:</b> {{contact.created_date}} </p>
        <p><b>Description:</b> {{contact.description}} </p>
        <p><b>Category:</b> {{contact.category.name}} </p>

        {% if contact.picture %}
            <p>
                <img src="{{contact.picture.url}}" alt="{{contact.first_name}} {{contact.last_name}}">
            </P>
        {% endif %}
        {% if user == contact.owner %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Update</a>
                <form action="{% url 'contact:delete' contact.id %}" method="POST" onsubmit="event.preventDefault(); showModal(this);">
                    {% csrf_token %}
                    <button class="btn btn-link btn-delete" type="submit">Delete</button>
                </form>
                <div id="deleteConfirmModal" class="modal">
                    <div class="modal-content ">
                        <p>Tem certeza de que deseja deletar este contato?</p>
                        <button class="btn btn-delete btn-delete-confirm " onclick="confirmDeletion()">Deletar</button>
                        <button class="btn btn-delete-confirm " onclick="closeModal()">Cancelar</button>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    

{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action="{{form_action}}"
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}        

    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{ field }}
          {{field.errors}}
          {% if field.help_text %}
            <p class="help-text">{{field.help_text}}</p>
          {% endif %}

        </div>

        {% if field.name == 'picture' and field.value.url%}
          <div class="fomr-group">
              <img src="{{field.value.url}}" alt=""> 
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

    </form>
  </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'contact:contact' contact.id %}">
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{contact.first_name}}
                        </td>
                        <td class="table-cel">
                            {{contact.last_name}}
                        </td>
                        <td class="table-cel">
                            {{contact.phone}}
                        </td>
                        <td class="table-cel">
                            {{contact.email}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Nenhum contato encontrado.
    </h1>
</div>

{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}

{% block content %}
  <div class="form-wrapper">

    <h2>Login</h2>

    {% if user.is_authenticated %}
        <p>
            Você fez login como {{user.username}}.
            clique <a href="{% url "contact:logout" %}">aqui</a> para sair.
            
        </p>
    {% else %}
        {% include "contact/partials/_user-form.html" %}
    {% endif %}
    
    
  </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}
  <div class="form-wrapper">

    <h2>Register</h2>

    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}

contact/templates/contact/user_update.html
{% extends "global/base.html" %}

{% block content %}
  <div class="form-wrapper">

    <h2>Update User</h2>

    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}